### PR TITLE
Add wast_resolve_names_* as a separate pass

### PR DESCRIPTION
**Pull request by binji**
This used to be handled by wasm_check_ast, but is clunkier than having a
separate pass.

### CODE REVIEW

**Comment by binji** [comment]
@sbc100 @KarlSchimpf ptal (looks like the failure on travis is a flake)

**Comment by binji** [comment]
Yeah, I think so. ast-validator? or maybe just ast-validate? I've been naming the files as nouns (reader/writer/etc.) but perhaps it makes less sense in this case.

**Comment by sbc100** [comment]
Why the ast- prefix on the filename?  alternatively, why isn't the new file called ast-resolve-names?

**Comment by binji** [comment]
Hm, good point. I guess I added it originally for the parser and lexer. But yeah, probably not needed for anything else, it's reasonable to assume that they work on the AST.

**Comment by sbc100** [comment]
Happy for this to land as-is, with any renaming as followup.

**Pull request closed without merging**
