### PR TITLE
Update spec tests

### PR DESCRIPTION
**Pull request by marcusb**

### CODE REVIEW

**Comment by marcusb** [comment]
@keithw

**Comment by marcusb** [comment]
Not sure if I should also run `./test/update-spec-tests.py` to add the new test cases, but those do not generally pass.

**Review by sbc100 — APPROVED** [review]
lgtm, I think we can worry about any news tests in separate PRs.

**Comment by sbc100** [comment]
(Will wait for @keithw approval before landing)

**Comment by keithw** [comment]
lgtm. An update that runs update-spec-tests.py is at #2001; this brings in the new tokens.wast test, which requires a change to the Wast lexer to get everything passing.

**Review by keithw — APPROVED** [review]

**Pull request merged**
