### PR TITLE
[wasmdump] Don't assume names section is in order

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by pipcet** [comment]
My understanding is the spec mandates that the name section is in order. We should probably just throw an error?

**Comment by sbc100** [comment]
I don't see anything in the spec about saying that the indexs have to be in order.  Perhaps I missed something?  I'm not sure if @lukewagner intended it perhaps?

**Comment by binji** [comment]
Ah, @pipcet is right: https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#name-map

> sequence of naming sorted by index

**Comment by pipcet** [comment]
Sorry for not providing the reference; yes, I meant the bit @binji quoted.

**Comment by sbc100** [comment]
Ah, I didn't notice this.  Thanks!

**Pull request closed without merging**
