### PR TITLE
run-tests.py works properly with python3

### LINKED ISSUE #1180: UnicodeDecodeError when parsing test/regress/regress-30.txt
When running the testsuite of 1.0.12, I'm getting this exception when `run_tests.py` is processing `test/regress/regress-30.txt`:

```
$ python3 -V
Python 3.7.4
$ test/run-tests.py --timeout=20 
Traceback (most recent call last):
  File "test/run-tests.py", line 952, in <module>
    sys.exit(main(sys.argv[1:]))
  File "test/run-tests.py", line 909, in main
    infos = GetAllTestInfo(test_names, status)
  File "test/run-tests.py", line 664, in GetAllTestInfo
    info.Parse(test_name)
  File "test/run-tests.py", line 484, in Parse
    for line in f.readlines():
  File "/usr/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 225: invalid start byte
```

### PR DESCRIPTION
**Pull request by binji**
Fixes #1180 and #1181.

### CODE REVIEW

**Comment by binji** [comment]
> CI?

What do you mean?

**Comment by sbc100** [comment]
Should we do some python3 testing CI if we want to avoid regressing this?

**Comment by binji** [comment]
Oh, I see what you mean. Yeah, I'll see about adding that to one of the configurations.

**Comment by binji** [comment]
OK, added it as a Github CI action. Pretty easy to do too!

**Pull request merged**
