### PR TITLE
Use threading, not multiprocessing, in run-tests

### PR DESCRIPTION
**Pull request by binji**
Hopefully this will fix the stability when running the tests on Travis.
On my machine, this does run 2x slower, but it's still pretty fast.

### CODE REVIEW

**Comment by binji** [comment]
@sbc100

**Comment by dschuff** [comment]
Interesting, I've usually found that going the other direction (threading->multiprocessing) makes things more reliable for python programs. Do you have any idea what's causing the flakiness?

**Comment by binji** [comment]
No, not sure. :-|

**Comment by dschuff** [comment]
well, it's worth a shot anyway, especially since you've already done the work. In general I would prefer multiprocessing over threading (it's a newer interface and as I said I believe it's easier to use and more reliable), so if this doesn't help the problem we should maybe revert it eventually.

**Comment by dschuff** [comment]
oh also a new github feature: you can explicitly request review from a particular person

**Comment by binji** [comment]
Neat!

**Comment by binji** [comment]
I think perhaps the issue is that I'm managing the queues, processes, and termination directly; perhaps using multiprocessing.Pool instead would fix the issues as well. It just seems like an annoying bug to track down, considering it only seems to happen on Travis.

**Comment by sbc100** [comment]
@dschuff for some reason my gut tells me the exact opposite.  i.e. multi-processing is a fragile hack who's only/main purpose in like to work around python's silly GIL implementation detail.  In that past I remember having trouble with multiprocessing and finding it less intuitive than multithreadin(which I'm used to from so many of other languages).   My intuition could be wrong / out-of-date though. 

No opinion on this change specifically though.

**Comment by dschuff** [comment]
@binji were you planning on trying something else instead of this? Or did you find through some other means that it didn't help?

**Comment by binji** [comment]
No, this was merged, it just didn't show up that way in GH for some reason.

**Pull request closed without merging**
