### PR TITLE
Version 1.0.29

### PR DESCRIPTION
**Pull request by sbc100**
See #1914

### CODE REVIEW

**Review by binji — APPROVED** [review]

**Comment by steven-johnson** [comment]
wait, what happened?

**Comment by sbc100** [comment]
Just a normal periodic release.  Nothing special.

**Comment by steven-johnson** [comment]
No, I mean the branch was deleted, and there is no 1.0.29 release.

**Comment by sbc100** [comment]
Oh this was just the PR to update the changlog.  I still need to create a release from this.  1 sec

**Pull request merged**
