### PR TITLE
Run wasm-interp on specific (exported) functions

### PR DESCRIPTION
**Pull request by amirbawab**
Closes: #198 

Minor changes allowing 'wasm-interp' to be executed for specific exported
wasm functions. Example syntax:

```
./wasm-interp                              \
-r "my_func" -a "i32:1" -a "i32:2", etc... \
file.wasm

./wasm-interp          \
-r "func_A" -a "f32:1" \
-r "func_A" -a "f32:2" \
-r "func_B" -a "i64:1" \
file.wasm
```

Currently supported types: i32, i64, f32, f64

### CODE REVIEW

**Comment by binji** [comment]
Wow, thanks for doing this! I just skimmed the code, but in general this looks good. @jgravelle-google can you do a more thorough review?

**Comment by keithw** [comment]
Closing as stale. :-( This would still be nice to have.

**Comment by raphamorim** [comment]
@keithw is this something is still interesting to have? I would be keen to work on it if needs any extra work on this PR.

**Comment by keithw** [comment]
If it would be helpful to you, I think we'd happily take a PR!

**Comment by raphamorim** [comment]
Sounds good @keithw! Will create a new PR and mention this one. Not sure if I like the way using `-r` and `-a` but we can iterate on API changes as well.

**Pull request closed without merging**
