### PR TITLE
Use 8 hex digits for wasm version rather than 6

### PR DESCRIPTION
**Pull request by pipcet**
Very definitely a cosmetic issue, but I think 0x00000001 or 0x1 are both preferrable to 0x000001.

### CODE REVIEW

**Comment by binji** [comment]
I'm fine with it either way. @sbc100, opinion?

**Comment by sbc100** [comment]
Not a big deal I guess, but perhaps just 0x1 is better.

**Comment by binji** [comment]
Agreed, do you mind switching it to just 0x1, @pipcet?

**Comment by pipcet** [comment]
Of course not, I was just being lazy and waiting for #395 to land first :-)

**Pull request merged**
