### PR TITLE
Version 1.0.33

### PR DESCRIPTION
**Pull request by keithw**
I think we're ready to tag 1.0.33 now.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by keithw** [comment]
Thank you! Please feel free to merge and do the release as you see fit, unless you want me to take a stab at it. (I haven't pushed our release pipeline before.)

**Comment by sbc100** [comment]
Please go ahead and create the release.

**Comment by keithw** [comment]
Done.

**Comment by steven-johnson** [comment]
I just updated Halide to use this release, and now compiling on OSX fails with:

```
/Users/srj/GitHub/Halide/build/release/_deps/wabt-src/src/sha256.cc:22:10: fatal error: 'picosha2.h' file not found
#include "picosha2.h"
         ^~~~~~~~~~~~
```

**Pull request merged**
