### PR TITLE
wasmdump: support multiple input files

### PR DESCRIPTION
**Pull request by sbc100**
This mimics how objdump behaves. Also makes the code more
readable.

Looking into adding a test for this but looks tricky with the current framework.

### CODE REVIEW

**Comment by sbc100** [comment]
Added a test

**Comment by sbc100** [comment]
Does the test change look good to you?

**Comment by binji** [comment]
I don't see a test...?

**Comment by sbc100** [comment]
Oops, forgot to add the new test file.  Also i changed test/run-wasmdump.py so that it runs wasmdump in a single invocation rather than once per file so we get implicit coverage already.

**Comment by binji** [comment]
Cool, looks good.

**Pull request merged**
