### PR TITLE
Rename wasm-opcodecnt to wasm-stats

### PR DESCRIPTION
**Pull request by SoniEx2**
This is a breaking change. Also uh, sorry, how do you re-generate the man pages and HTML docs?

(also shoutout to https://github.com/WebAssembly/wabt/commit/61c910bfcf9629db877f4f8a4f445fec282fec7d#diff-cd45c62ec9442a1431d03057a70247b778e5dde436cc7ae4c412d5f0e989cdeeR71 for long time typo!)

### CODE REVIEW

**Review by sbc100 — COMMENTED** [review]
lgtm, with the man page update

**Comment by SoniEx2** [comment]
alright, uh... how do you do that? we see there's a help2man.lua but we're not really sure how it's supposed to be used... it doesn't seem to have documentation.

(also we don't know how to manually write/update man pages, either)

sorry

**Comment by sbc100** [comment]
> alright, uh... how do you do that? we see there's a help2man.lua but we're not really sure how it's supposed to be used... it doesn't seem to have documentation.
> 
> (also we don't know how to manually write/update man pages, either)
> 
> sorry

I'm afraid I don't know either.   That stuff was written by @binji who is no longer actively involved.   He may remember and reply here, but failing that you might need to dive in and figure it out.

**Comment by binji** [comment]
I don't think I added this, it was an external contributor. So unfortunately, I don't really know how it was meant to be updated either.

**Comment by sbc100** [comment]
Looking at the commit message it looks like you use it like this:

```
wabt-tool --help | lua help2man.lau
```

See #2004

**Comment by sbc100** [comment]
> Looking at the commit message it looks like you use it like this:
> 
> ```
> wabt-tool --help | lua help2man.lau
> ```
> 
> See #2004

(You could also just rename the existing man page and search and replace the name)

**Comment by SoniEx2** [comment]
tech debt aside, this should be good to go

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
