### PR TITLE
Move executable sources to src/exe

### PR DESCRIPTION
**Pull request by binji**

### CODE REVIEW

**Comment by dschuff** [comment]
`src/exe` was surprising to me ("we have executables as source? are they checked-in binaries"). Maybe `src/tools` would be clearer? It would separate them from the common code (which, if it became more diverse, could be separated into different libs a la `src/lib`). LLVM and Binaryen have similar structure.

**Comment by binji** [comment]
sgtm, I'll rename after landing the wastfmt change

**Comment by sbc100** [comment]
I agree 'exe' sounds wrong.  Its a windows-ism at best. 

I like src/lib/ or src/libwabt/ for library sources.. and just src/ for the entry points.

**Comment by binji** [comment]
I'd like src/lib better if we go that route. I like src/tools for now, though.

**Pull request merged**
