### PR TITLE
Updates for Memory64 proposal tests from latest `testsuite`

### PR DESCRIPTION
**Pull request by aardappel**
This involves changes for Memory64, SIMD, and misc others.

WiP - No need to review yet.. trying to test with CI

### CODE REVIEW

**Comment by aardappel** [comment]
This PR is similar to https://github.com/WebAssembly/wabt/pull/1553, but also fixes Memory64 problems. It doesn't yet fix all the SIMD problems the other PR fixes, though. And neither one knows how to fix the `func.wast` related problems uniformly.

**Comment by binji** [comment]
It seems like it may be better to land #1553, then land this change on top. The `func.wast` issues are probably best to fix in another PR.

**Comment by binji** [comment]
Now that #1553 landed, would you mind updating this PR?

**Review by binji — APPROVED** [review]
lgtm!

**Pull request merged**
