### PR TITLE
Update SIMD support

### PR DESCRIPTION
**Pull request by darinmorrison**
This PR updates SIMD support corresponding to changes in the [WebAssembly/simd](https://github.com/WebAssembly/simd) proposal repo from the following PRs:

https://github.com/WebAssembly/simd/pull/321
https://github.com/WebAssembly/simd/pull/322
https://github.com/WebAssembly/simd/pull/341
https://github.com/WebAssembly/simd/pull/344

This should not be merged until https://github.com/WebAssembly/testsuite/pull/32 is merged since it needs the updated testsuite using the new syntax for the SIMD tests.

For the moment I have pointed the `third_party/testsuite` to my local branch which has the recent changes from  [WebAssembly/simd](https://github.com/WebAssembly/simd) merged.

Note that in the PR I referenced for the [WebAssembly/testsuite](https://github.com/WebAssembly/testsuite) there will be additional (probably minor) breakage from recent changes in other proposal repos but I didn't include fixes for all of those here since I wanted this PR to focus on SIMD.

### CODE REVIEW

**Comment by darinmorrison** [comment]
I've updated the PR now that [WebAssembly/testsuite](https://github.com/WebAssembly/testsuite) has been synchronized with the [WebAssembly/simd](https://github.com/WebAssembly/simd) repo upstream.

All of the simd tests are still passing but one of the new (unrelated) tests pulled in from [WebAssembly/spec](https://github.com/WebAssembly/spec) does not pass and I'm not sure how to fix it.

The test is [this one](https://github.com/WebAssembly/testsuite/blob/18f83401a47a0e43772cf7d9f216e994bf7c7fa6/func.wast#L447-L457) which was added from https://github.com/WebAssembly/spec/pull/1213.

**Comment by aardappel** [comment]
Looks like the `func.wast` test is still failing.. I was actually looking at that earlier, but no idea what the problem is.

Is this the root cause? `out/test/spec/func.wast:448: expected module to be malformed: "out/test/spec/func/func.3.wat"` ? Seems some `quote` modules where added.

**Comment by darinmorrison** [comment]
> Is this the root cause? `out/test/spec/func.wast:448: expected module to be malformed: "out/test/spec/func/func.3.wat"` ? Seems some `quote` modules where added.

@aardappel Yes, that's the one I wasn't sure how to fix either.

It's related to this issue: https://github.com/WebAssembly/spec/pull/1213.

There's a similar test above it that doesn't use the quoted module ([here](https://github.com/WebAssembly/testsuite/blob/18f83401a47a0e43772cf7d9f216e994bf7c7fa6/func.wast#L435-L445)) and that one does fail (correctly).

The problem seemingly has to do with the fact that the type index ([here](https://github.com/WebAssembly/testsuite/blob/18f83401a47a0e43772cf7d9f216e994bf7c7fa6/func.wast#L454)) is out of range and should trigger the `malformed` error for the quoted module, but doesn't.

Probably there is some sort of validation that has to happen when processing the quoted module but I don't understand enough about the internals of `wabt` to know how to fix it.

**Comment by aardappel** [comment]
@rossberg (and @binji if around) any guidance what the new test in https://github.com/WebAssembly/spec/pull/1213 is supposed to do? Both myself and @darinmorrison so far have failed to fix it in WABT (see error above).

**Comment by rossberg** [comment]
@aardappel, can you be more specific? There is more than one test there.

**Comment by rossberg** [comment]
Ah, sorry, didn't read up-thread. Let me look.

**Comment by rossberg** [comment]
Okay, so the difference between this test and the preceding one is that the function also lists a parameter explicitly. This is a form of syntactic sugar in the text format alone, that has no correspondence in the binary format, and thus the AST. Consequently, it has to be desugared in the parser. But desugaring it requires knowing the actual type. So in order to do that, the parser (not just the validator) has to know and access the type definition for type 2 in this case, which doesn't exist. Since it's the parser failing this time, it produces malformed, not invalid.

It is rather annoying, but I'm not sure what the alternative could be, given that we have this sugar. What does wabt produce for this test atm?

**Comment by darinmorrison** [comment]
> What does wabt produce for this test atm?

@rossberg Currently `wabt` doesn't produce any error on the second test with the quoted module.

> Okay, so the difference between this test and the preceding one is that the function also lists a parameter explicitly. This is a form of syntactic sugar in the text format alone, that has no correspondence in the binary format, and thus the AST. Consequently, it has to be desugared in the parser.

Alright, I think that makes sense.

I know almost nothing about the internals of `wabt`. This was my first PR, just intended to fix the SIMD tests for some other tools that use `wabt` downstream.

However, I think there may be something more fundamental going wrong with how `wabt` is handling the test because even if you remove the parameter (below) so that the quoted module is like the first test, it still gives no error:

```wasm
(assert_malformed
  (module quote
    "(func $f (result f64) (f64.const 0))"  ;; adds implicit type definition
    "(func $g (param i32))"                 ;; reuses explicit type definition
    "(func $h (result f64) (f64.const 1))"  ;; reuses implicit type definition
    "(type $t (func (param i32)))"

    "(func (type 2))"  ;; does not exist
  )
  "unknown type"
)
```

Just to be clear, should the above give an `invalid` error? (Not `malformed` since it doesn't involve the desugaring?)

**Comment by rossberg** [comment]
Yes, that should be invalid, just like the preceding test.

**Comment by aardappel** [comment]
@darinmorrison any progress on fixing that last issue?

**Comment by darinmorrison** [comment]
@aardappel Unfortunately I don't really know how to fix that test. I think this will need some input from @binji or @sbc100 or some other maintainer who is more familiar with the internals of wabt.

**Comment by aardappel** [comment]
Ok, I will have another look.

**Comment by aardappel** [comment]
Ok, in `CheckFuncTypeVarMatchesExplicit` try adding this to the `if (func_type)` check:

```
    } else {
      errors->emplace_back(ErrorLevel::Error, loc, "type index out of range");
      result = Result::Error;
```

That made `func.wast` pass for me, and didn't seem to break any other tests.

**Comment by darinmorrison** [comment]
@aardappel Do you mean like this?

```cpp
Result CheckFuncTypeVarMatchesExplicit(const Location& loc,
                                       const Module& module,
                                       const FuncDeclaration& decl,
                                       Errors* errors) {
  Result result = Result::Ok;
  if (decl.has_func_type) {
    const FuncType* func_type = module.GetFuncType(decl.type_var);
    if (func_type) {
      result |=
          CheckTypes(loc, decl.sig.result_types, func_type->sig.result_types,
                     "function", "result", errors);
      result |=
          CheckTypes(loc, decl.sig.param_types, func_type->sig.param_types,
                     "function", "argument", errors);
    } else {
      errors->emplace_back(ErrorLevel::Error, loc, "type index out of range");
      result = Result::Error;
    }
  }
  return result;
}
```

Maybe I'm missing something but when I re-run `cmake --build out --target run-tests` after that change, I get several new failing cases:

```
**** FAILED ******************************************************************
- test/spec/bulk-memory-operations/imports.txt
    /home/dwm/development/WebAssembly/wabt/out/wast2json out/test/spec/bulk-memory-operations/imports.wast -o out/test/spec/bulk-memory-operations/imports/imports.json --enable-bulk-memory
- test/spec/call_indirect.txt
    /home/dwm/development/WebAssembly/wabt/out/wast2json out/test/spec/call_indirect.wast -o out/test/spec/call_indirect/call_indirect.json
- test/spec/func.txt
    /home/dwm/development/WebAssembly/wabt/out/wast2json out/test/spec/func.wast -o out/test/spec/func/func.json
- test/spec/func_ptrs.txt
    /home/dwm/development/WebAssembly/wabt/out/wast2json out/test/spec/func_ptrs.wast -o out/test/spec/func_ptrs/func_ptrs.json
- test/spec/imports.txt
    /home/dwm/development/WebAssembly/wabt/out/wast2json out/test/spec/imports.wast -o out/test/spec/imports/imports.json
- test/spec/reference-types/call_indirect.txt
    /home/dwm/development/WebAssembly/wabt/out/wast2json out/test/spec/reference-types/call_indirect.wast -o out/test/spec/reference-types/call_indirect/call_indirect.json --enable-reference-types
- test/spec/reference-types/imports.txt
    /home/dwm/development/WebAssembly/wabt/out/wast2json out/test/spec/reference-types/imports.wast -o out/test/spec/reference-types/imports/imports.json --enable-reference-types
- test/wasm2c/spec/call_indirect.txt
    /usr/bin/python3 /home/dwm/development/WebAssembly/wabt/test/run-spec-wasm2c.py out/test/wasm2c/spec/call_indirect.txt --bindir=/home/dwm/development/WebAssembly/wabt/out --no-error-cmdline -o out/test/wasm2c/spec/call_indirect
- test/wasm2c/spec/func_ptrs.txt
    /usr/bin/python3 /home/dwm/development/WebAssembly/wabt/test/run-spec-wasm2c.py out/test/wasm2c/spec/func_ptrs.wast --bindir=/home/dwm/development/WebAssembly/wabt/out --no-error-cmdline -o out/test/wasm2c/spec/func_ptrs
- test/wasm2c/spec/func.txt
    /usr/bin/python3 /home/dwm/development/WebAssembly/wabt/test/run-spec-wasm2c.py out/test/wasm2c/spec/func.txt --bindir=/home/dwm/development/WebAssembly/wabt/out --no-error-cmdline -o out/test/wasm2c/spec/func
- test/wasm2c/spec/imports.txt
    /usr/bin/python3 /home/dwm/development/WebAssembly/wabt/test/run-spec-wasm2c.py out/test/wasm2c/spec/imports.wast --bindir=/home/dwm/development/WebAssembly/wabt/out --no-error-cmdline -o out/test/wasm2c/spec/imports
FAILED: CMakeFiles/run-tests 
```

For comparison, before the change (just with this current PR), this is the output I get:

```
**** FAILED ******************************************************************
- test/spec/func.txt
    /home/dwm/development/WebAssembly/wabt/out/spectest-interp out/test/spec/func/func.json
FAILED: CMakeFiles/run-tests 
```

Was there maybe another change that needed to be included?

**Comment by aardappel** [comment]
Did you run `run-tests.py -r` to update outputs?

**Comment by darinmorrison** [comment]
> Did you run `run-tests.py -r` to update outputs?

@aardappel Yes, I did try that with individual tests but I'm still getting errors.

Running `run-tests.py -r` produces the following:

```
**** FAILED ******************************************************************
- test/spec/bulk-memory-operations/imports.txt
    /home/dwm/development/WebAssembly/wabt/bin/wast2json out/test/spec/bulk-memory-operations/imports.wast -o out/test/spec/bulk-memory-operations/imports/imports.json --enable-bulk-memory
- test/spec/call_indirect.txt
    /home/dwm/development/WebAssembly/wabt/bin/wast2json out/test/spec/call_indirect.wast -o out/test/spec/call_indirect/call_indirect.json
- test/spec/func.txt
    /home/dwm/development/WebAssembly/wabt/bin/wast2json out/test/spec/func.wast -o out/test/spec/func/func.json
- test/spec/func_ptrs.txt
    /home/dwm/development/WebAssembly/wabt/bin/wast2json out/test/spec/func_ptrs.wast -o out/test/spec/func_ptrs/func_ptrs.json
- test/spec/imports.txt
    /home/dwm/development/WebAssembly/wabt/bin/wast2json out/test/spec/imports.wast -o out/test/spec/imports/imports.json
- test/spec/reference-types/call_indirect.txt
    /home/dwm/development/WebAssembly/wabt/bin/wast2json out/test/spec/reference-types/call_indirect.wast -o out/test/spec/reference-types/call_indirect/call_indirect.json --enable-reference-types
- test/spec/reference-types/imports.txt
    /home/dwm/development/WebAssembly/wabt/bin/wast2json out/test/spec/reference-types/imports.wast -o out/test/spec/reference-types/imports/imports.json --enable-reference-types
- test/wasm2c/spec/call_indirect.txt
    /usr/bin/python3 /home/dwm/development/WebAssembly/wabt/test/run-spec-wasm2c.py out/test/wasm2c/spec/call_indirect.txt --bindir=/home/dwm/development/WebAssembly/wabt/bin --no-error-cmdline -o out/test/wasm2c/spec/call_indirect
- test/wasm2c/spec/func.txt
    /usr/bin/python3 /home/dwm/development/WebAssembly/wabt/test/run-spec-wasm2c.py out/test/wasm2c/spec/func.txt --bindir=/home/dwm/development/WebAssembly/wabt/bin --no-error-cmdline -o out/test/wasm2c/spec/func
- test/wasm2c/spec/func_ptrs.txt
    /usr/bin/python3 /home/dwm/development/WebAssembly/wabt/test/run-spec-wasm2c.py out/test/wasm2c/spec/func_ptrs.wast --bindir=/home/dwm/development/WebAssembly/wabt/bin --no-error-cmdline -o out/test/wasm2c/spec/func_ptrs
- test/wasm2c/spec/imports.txt
    /usr/bin/python3 /home/dwm/development/WebAssembly/wabt/test/run-spec-wasm2c.py out/test/wasm2c/spec/imports.wast --bindir=/home/dwm/development/WebAssembly/wabt/bin --no-error-cmdline -o out/test/wasm2c/spec/imports
```

If you were able to get it to work (with the tests passing on CI), can you make your branch available? From that, I could just cherry-pick the commit into this PR.

**Comment by aardappel** [comment]
weird, I don't get those errors, instead I get some remaining SIMD errors I haven't solved yet.. I may make a PR later and we can compare

**Comment by aardappel** [comment]
Ok, my changes are here, and indeed also create these new `wasm2c` problems.. apparently because these don't run on Windows:
https://github.com/WebAssembly/wabt/pull/1560

It may be easiest to wait until @binji is back rather than try to debug this further

**Comment by binji** [comment]
Sorry for the long delay on resolving this. Is `func.wast` the only issue? If so, probably the easiest thing to do is change the expectation for that test to failure, and we can file a bug and resolve it separately.

It looks like other than this problem, the rest of the PR is relatively straightforward.

**Comment by darinmorrison** [comment]
@binji Yes, it's just the one test in `func.wast`. I think I can update the PR to expect that test to fail. Will take a look at that soon.

**Comment by darinmorrison** [comment]
@binji can you tell me what I need to change in order to mark the `func.wast` test as expected to fail? I tried a few things that didn't work and I guess I'm not really sure how to do that.

**Comment by darinmorrison** [comment]
@binji this should be good to go now I think.

**Review by binji — APPROVED** [review]
Awesome, thanks for doing this! lgtm

**Pull request merged**
