### PR TITLE
Add color output in SourceErrorHandler

### PR DESCRIPTION
**Pull request by binji**

### CODE REVIEW

**Comment by binji** [comment]
Good idea, I was looking at [chalk](https://github.com/chalk/supports-color/blob/master/index.js) to see how they check for a color terminal. Seems pretty complex, so I wanted to punt until we have users who can test them. They seem to have added a `FORCE_COLOR` environment variable as a top-level override, so maybe we should just follow that.

**Comment by sbc100** [comment]
yuk:
```if ('TRAVIS' in env || env.CI === 'Travis') {
			return 1;
```

yes an override env var sounds good.  Happy to be in a followup CL

**Comment by binji** [comment]
Looks like `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is only supported in windows 10, so we should fall back to `SetConsoleTextAttribute` like binaryen does.

**Comment by binji** [comment]
OK, for now it's win10 only, and color output is disabled on Windows otherwise. ptal

**Comment by binji** [comment]
Yeah, I'll add a test.

**Comment by binji** [comment]
Also added ability to set environment variables in test, PTAL

**Pull request merged**
