### PR TITLE
add minimal manpages (mdoc-formatted)

### LINKED ISSUE #417: Manual pages
Hello,

After installing `wabt` through Homebrew, I noticed none of the executables had a corresponding manpage.

If assistance is needed, I'd be happy to write them for you. =) I thought I'd ask first instead of submit a PR up-front, as not all maintainers are up to maintaining manpages in addition to Markdown-based docs. Particularly when the subject is very build-centric in nature.

Let me know if there's anything I can do.

### PR DESCRIPTION
**Pull request by rrrapha**
Resolves #417

### CODE REVIEW

**Comment by rrrapha** [comment]
The information is mostly taken from README.md and extracted from the usage output. Only the tools mentioned in README.md are covered.
The manual pages are not hooked up to the build system yet.

**Comment by binji** [comment]
Thanks! I don't know the syntax at all, but just a quick glance looks good to me.

**Comment by sbc100** [comment]
Shouldn't they be added to the `make install` target too?

**Comment by binji** [comment]
Yeah, but I think it's fine to do that in another PR.

**Pull request merged**
