### PR TITLE
Add i{32,64}.extend{8,16,32}_s operators

### PR DESCRIPTION
**Pull request by binji**
Also add thread feature (via `--enable-threads`).

### CODE REVIEW

**Comment by sbc100** [comment]
lgtm, but why are these new sign extend operators linked to threading?

**Comment by binji** [comment]
It's a bit weird, but they were introduced w/ the threading proposal (because they'll work in tandem w/ the atomic zero-extending instructions). Do you think it's worth separating them out? It seems like it would be annoying to have to pass two flags to use sign-extension and atomics in that case.

**Comment by dschuff** [comment]
I think one flag makes sense since it enables both features.

**Comment by dschuff** [comment]
Or I guess I should say, enables both features in the platform. Might not matter so much for WABT, but even for more user-facing tools like emscripten, there will just be one control and one feature test.

**Pull request merged**
