### PR TITLE
binary-reader-ir: Track usage of exception handling in features_used

### PR DESCRIPTION
**Pull request by SoniEx2**

### CODE REVIEW

**Comment by SoniEx2** [comment]
@sbc100

**Review by sbc100 — APPROVED** [review]
How about "binary-reader-ir: track usage of exception handling in features_used"?

**Comment by SoniEx2** [comment]
sure!

**Comment by keithw** [comment]
lgtm, but shouldn't this be part of #2470 ?

**Comment by SoniEx2** [comment]
we're splitting that into like 100 tiny commits because it makes review easier apparently

**Pull request merged**
