### PR TITLE
Support new dylink.0 custom section format

### PR DESCRIPTION
**Pull request by sbc100**
This section is now based on sub-sections making it more
extensible.

See also:
llvm change: https://reviews.llvm.org/D109595
binaryen change: https://github.com/WebAssembly/binaryen/pull/4141

### CODE REVIEW

**Comment by dschuff** [comment]
I guess `onSymbol` would be useful for something like a `wabt-nm` but isn't used now?

**Comment by dschuff** [comment]
Actually, if onSymbol currently actually works, maybe we should leave it (and maybe add a simple dumper) until I'm done investigating how we want LLVM to treat symbols (e.g. section vs binary offsets). It might be useful to check against LLVM.

**Review by dschuff — APPROVED** [review]
LGTM otherwise

**Comment by sbc100** [comment]
> I guess `onSymbol` would be useful for something like a `wabt-nm` but isn't used now?

`onSymbol` was replaced with the more specific `OnFunctionSymbol`, `OnGlobalSymbol`, etc, back in #769, I think this was just left over by mistake.

**Comment by sbc100** [comment]
> > I guess `onSymbol` would be useful for something like a `wabt-nm` but isn't used now?
> 
> `onSymbol` was replaced with the more specific `OnFunctionSymbol`, `OnGlobalSymbol`, etc, back in #769, I think this was just left over by mistake.

I split that out into its own CL anyway.

**Pull request merged**
