### PR TITLE
Switch python indentation from 2-space to 4-space

### PR DESCRIPTION
**Pull request by sbc100**
pep8 specifies 4 space indentation.  The use of 2 spaces is, I believe,
a historical anomaly where certain large organizations such as google
chose 2 over 4 and have yet to make the switch.

For a project like wabt with little python code I think the cost of
switching is small enough to justify the churn.

### CODE REVIEW

**Comment by Alhadis** [comment]
> I don't like 4-space much

Wouldn't it be great if there was a configurable yet unambiguous way to encode a tabstop directly inside a file without making assumptions about its width? And somehow have this semantic information understood by even the most rudimentary of text-editors?

Oh wait, tabs are bad... 😉 But people can never explain why, only remind you of the *main reason* to use them. *“They have different sizes in different editors…”*

But, like, tabs are also evil, and stuff. Probably also taboo in three world religions, banned in China, the real cause of the Bronze Age Collapse, and unequivocally spawned from parasitic alien life which [infected Earth](https://www.youtube.com/watch?v=SST5NjFSYEo) during the Stone Age... oh never mind, I'm thinking of EBCDIC.

> \*holds his breath and smashes that sexy little <kbd>SUBMIT</kbd> button\*

*Geronimoooooooo!*

**Comment by tlively** [comment]
:joy::joy::joy:

... but seriously, tabs are evil :smiling_imp:

**Comment by Alhadis** [comment]
👌 It's okay, pick whatever tabstop you want, because I'm reformatting your code before reading it anyway. No, seriously, I'm [habitually running this](https://github.com/Alhadis/Unfuck-Tabstops) any time I'm loading most projects on GitHub. 👍 😉 Say what you want about my intolerance, you can't fault me for channeling that anger into a solution, instead of, y'know, whining about it at [`/r/bikeshed`](https://www.reddit.com/r/bikeshed/).

Also, uh, that subreddit, [`/r/bikeshed`](https://www.reddit.com/r/bikeshed/)? Its posts seem to be a mix about hacker-related stuff and stuff about... actual bicycles. I really have no words for what this is making me feel right now.

**Comment by sbc100** [comment]
Perhaps we should add an extra clause to our apache license that forbids refomatting of the code to contain tabs?    It would make the license non-free, but it would also help reduce evil in the world.

**Comment by mohe2015** [comment]
https://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces should be the correct way in my opinion.

**Comment by Alhadis** [comment]
@mohe2015 That's what I do, but I always keep them separated by at least one non-whitespace character, ensuring there's no ambiguity.

**Pull request merged**
