### PR TITLE
Update demos to add JS eval to wat2wasm demo

### PR DESCRIPTION
**Pull request by krisselden**
Some minor redesign of demos.

image

### CODE REVIEW

**Comment by binji** [comment]
Very cool! Thanks for doing this. The only thing I was wondering was about whether it makes sense to use template strings and `let`, but I guess they've been around for a long time now so there's not much worry.

**Comment by binji** [comment]
By the way, can you join the [community group](https://www.w3.org/community/webassembly/)? It's required to contribute to WebAssembly GH projects. Sorry I forgot to mention this before.

**Comment by krisselden** [comment]
As far as I know, there is no browser that supports WebAssembly that does not also support the features I used.

I created an account and filled out the form requesting to join as a collaborator.

**Comment by binji** [comment]
> As far as I know, there is no browser that supports WebAssembly that does not also support the features I used.

Right, but the library was compiled w/ asm.js so didn't require WebAssembly before. In any case, I think it should be fine.

> I created an account and filled out the form requesting to join as a collaborator.

Thanks!

**Pull request merged**
