### PR TITLE
test(interp): Move legacy exception handling tests (NFC)

### PR DESCRIPTION
**Pull request by SoniEx2**

### CODE REVIEW

**Comment by sbc100** [comment]
It looks like maybe we can completely remove `third_party/testsuite_legacy` now that https://github.com/WebAssembly/testsuite/pull/81 has been merged?

**Comment by SoniEx2** [comment]
would have to update testsuite first

**Comment by sbc100** [comment]
Ah I see.  Do you still want to land this change first?

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
Can you rebase and this should then auto-merge

**Comment by SoniEx2** [comment]
you forgot this:

>  auto-merge was automatically disabled
> Head branch was pushed to by a user without write access

but anyway

**Review by keithw — APPROVED** [review]

**Pull request merged**
