### PR TITLE
Update wasm-interp.cc

### PR DESCRIPTION
**Pull request by Issue-03**
changed to "initializing"

### CODE REVIEW

**Comment by binji** [comment]
Thanks for fixing! It looks good, but you need to fix the tests too. Take a look at https://github.com/WebAssembly/wabt/blob/master/test/README.md#writing-new-tests, specifically passing the `-r` flag to rebaseline the tests.

**Comment by Issue-03** [comment]
Hello, @binji 
Sorry, I am a beginner at Open Source, so I did not know why it was failing. I read the the file indicated by you, but did not understand. Can you please help?
Thank you.

**Comment by binji** [comment]
It's failing because when the code is compiled, it produces a new output with the correct spelling. There are tests in the repo that check the output of various tools, and will error-out when the output doesn't match the expected output.

In this case, the `bad-data-size.txt` test is failing. Here's the output from one of the CI bots:

```
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1 +1 @@
  -error initialiazing module: out of bounds memory access: data segment is out of bounds: [0, 8) >= max value 0
  +error initializing module: out of bounds memory access: data segment is out of bounds: [0, 8) >= max value 0
```

You can fix this by compiling the code, then running the tests with the `-r` flag:

```
$ test/run-tests.py -r bad-data-size.txt
```

This will run the tests, capture the output, and replace the expected text automatically.

**Comment by binji** [comment]
This was fixed here: https://github.com/WebAssembly/wabt/pull/1410

**Pull request closed without merging**
